version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: denshtan/foodgram_backend
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    image: denshtan/foodgram_frontend
    env_file: ./.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: denshtan/foodgram_gateway
    env_file: ./.env
    depends_on:
      - backend
      - frontend
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    ports:
      - 9000:80
